name: e2e-tests
signing_provider:
  turnkey:
    api_public_key: ${TURNKEY_PUBLIC_KEY}
    api_private_key: ${TURNKEY_PRIVATE_KEY}
    organization_id: ${TURNKEY_ORG_ID}
    wallet_id: ${TURNKEY_WALLET_ID}
networks:
  - name: local_anvil
    chain_id: 31337
    provider_urls:
      - http://127.0.0.1:8545
    block_explorer_url: http://localhost:8545
    enable_sending_blobs: true
    automatic_top_up:
      from:
        # safe: "0xcfe267de230a234c5937f18f239617b7038ec271" # NEED TO TEST
        relayer:
          address: '0x655B2B8861D7E911D283A05A5CAD042C157106DA'
          internal_only: false
      relayers:
        - "0x1C09DF15FB12656420033EB58067EC9406EF0E26"
        - "0x6F3E343161C4B905342015AD20A5C492ADFB730E"
        - "0x68333AE8A21E1F768B20DB409486BE2D569A5258"
      native:
        min_balance: "50"
        top_up_amount: "100"
      erc20_tokens:
        - address: "0x99bba657f2bbc93c02d617f8ba121cb8fc104acf" # Deterministic TestToken address
          min_balance: "100"
          top_up_amount: "500"
    permissions:
      - relayers:
          - "0x1c09df15fb12656420033eb58067ec9406ef0e26"
        allowlist:
          - "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
        disable_native_transfer: false
        # TODO: need to test these
        disable_personal_sign: false
        disable_typed_data_sign: false
        disable_transactions: false
      - relayers:
          - "0x6f3e343161c4b905342015ad20a5c492adfb730e"
        allowlist:
          - "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
          - "0x70e0ba845a1a0f2da3359c97e0285013525ffc49"
        disable_native_transfer: true
webhooks:
  - endpoint: http://localhost:8546/webhook
    shared_secret: ${RRELAYER_WEBHOOK_SHARED_SECRET}
    networks:
      - local_anvil
rate_limits:
  user_limits:
    per_relayer:
      interval: "minute"
      transactions: 1
      signing_operations: 1
    global:
      interval: "minute"
      transactions: 3
      signing_operations: 3
# TODO: needs testing
#  relayer_limits:
#    interval: "minute"
#    transactions: 5
#    signing_operations: 100
api_config:
  port: 3000
  authentication_username: ${RRELAYER_AUTH_USERNAME}
  authentication_password: ${RRELAYER_AUTH_PASSWORD}